In [119]:
import pandas as pd

In [137]:
df = pd.read_csv('loan_data_set.csv')
df.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [122]:
na_variables = []
for col in df.columns:
    missing_percentage = df[col].isna().mean()
    if missing_percentage > 0 :
        na_variables.append(col)
print(na_variables)

['Gender', 'Married', 'Dependents', 'Self_Employed', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History']

In [123]:
df[['Gender','Married','Self_Employed']].info()
df[df[['Gender','Married','Self_Employed']].isnull().any(axis=1)]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender         601 non-null    object
 1   Married        611 non-null    object
 2   Self_Employed  582 non-null    object
dtypes: object(3)
memory usage: 14.5+ KB

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
11,LP001027,Male,Yes,2,Graduate,NaN,2500,1840.0,109.0,360.0,1.0,Urban,Y
19,LP001041,Male,Yes,0,Graduate,NaN,2600,3500.0,115.0,NaN,1.0,Urban,Y
23,LP001050,NaN,Yes,2,Not Graduate,No,3365,1917.0,112.0,360.0,0.0,Rural,N
24,LP001052,Male,Yes,1,Graduate,NaN,3717,2925.0,151.0,360.0,NaN,Semiurban,N
29,LP001087,Female,No,2,Graduate,NaN,3750,2083.0,120.0,360.0,1.0,Semiurban,Y
30,LP001091,Male,Yes,1,Graduate,NaN,4166,3369.0,201.0,360.0,NaN,Urban,N
95,LP001326,Male,No,0,Graduate,NaN,6782,0.0,NaN,360.0,NaN,Urban,N
104,LP001357,Male,NaN,NaN,Graduate,No,3816,754.0,160.0,360.0,1.0,Urban,Y
107,LP001370,Male,No,0,Not Graduate,NaN,7333,0.0,120.0,360.0,1.0,Rural,N
111,LP001387,Female,Yes,0,Graduate,NaN,2929,2333.0,139.0,360.0,1.0,Semiurban,Y
114,LP001398,Male,No,0,Graduate,NaN,5050,0.0,118.0,360.0,1.0,Semiurban,Y
126,LP001448,NaN,Yes,3+,Graduate,No,23803,0.0,370.0,360.0,1.0,Rural,Y
158,LP001546,Male,No,0,Graduate,NaN,2980,2083.0,120.0,360.0,1.0,Rural,Y
170,LP001581,Male,Yes,0,Not Graduate,NaN,1820,1769.0,95.0,360.0,1.0,Rural,Y
171,LP001585,NaN,Yes,3+,Graduate,No,51763,0.0,700.0,300.0,1.0,Urban,Y
188,LP001644,NaN,Yes,0,Graduate,Yes,674,5296.0,168.0,360.0,1.0,Rural,Y
218,LP001732,Male,Yes,2,Graduate,NaN,5000,0.0,72.0,360.0,0.0,Semiurban,N
228,LP001760,Male,NaN,NaN,Graduate,No,4758,0.0,158.0,480.0,1.0,Semiurban,Y
231,LP001768,Male,Yes,0,Graduate,NaN,3716,0.0,42.0,180.0,1.0,Rural,Y
236,LP001786,Male,Yes,0,Graduate,NaN,5746,0.0,255.0,360.0,NaN,Urban,N
268,LP001883,Female,No,0,Graduate,NaN,3418,0.0,135.0,360.0,1.0,Rural,N
295,LP001949,Male,Yes,3+,Graduate,NaN,4416,1250.0,110.0,360.0,1.0,Urban,Y
314,LP002024,NaN,Yes,0,Graduate,No,2473,1843.0,159.0,360.0,1.0,Rural,N
333,LP002101,Male,Yes,0,Graduate,NaN,63337,0.0,490.0,180.0,1.0,Urban,Y
334,LP002103,NaN,Yes,1,Graduate,Yes,9833,1833.0,182.0,180.0,1.0,Urban,Y
336,LP002110,Male,Yes,1,Graduate,NaN,5250,688.0,160.0,360.0,1.0,Rural,Y
344,LP002128,Male,Yes,2,Graduate,NaN,2583,2330.0,125.0,360.0,1.0,Rural,Y
374,LP002209,Female,No,0,Graduate,NaN,2764,1459.0,110.0,360.0,1.0,Urban,Y
380,LP002226,Male,Yes,0,Graduate,NaN,3333,2500.0,128.0,360.0,1.0,Semiurban,Y
385,LP002237,Male,No,1,Graduate,NaN,3667,0.0,113.0,180.0,1.0,Urban,Y
411,LP002319,Male,Yes,0,Graduate,NaN,6256,0.0,160.0,360.0,NaN,Urban,Y
432,LP002386,Male,No,0,Graduate,NaN,12876,0.0,405.0,360.0,1.0,Semiurban,Y
435,LP002393,Female,NaN,NaN,Graduate,No,10047,0.0,NaN,240.0,1.0,Semiurban,Y
447,LP002435,Male,Yes,0,Graduate,NaN,3539,1376.0,55.0,360.0,1.0,Rural,N
460,LP002478,NaN,Yes,0,Graduate,Yes,2083,4083.0,160.0,360.0,NaN,Semiurban,Y
463,LP002489,Female,No,1,Not Graduate,NaN,5191,0.0,132.0,360.0,1.0,Semiurban,Y
467,LP002501,NaN,Yes,0,Graduate,No,16692,0.0,110.0,360.0,1.0,Semiurban,Y
468,LP002502,Female,Yes,2,Not Graduate,NaN,210,2917.0,98.0,360.0,1.0,Semiurban,Y
477,LP002530,NaN,Yes,2,Graduate,No,2873,1872.0,132.0,360.0,0.0,Semiurban,N
507,LP002625,NaN,No,0,Graduate,No,3583,0.0,96.0,360.0,1.0,Urban,N
535,LP002732,Male,No,0,Not Graduate,NaN,2550,2042.0,126.0,360.0,1.0,Rural,Y
542,LP002753,Female,No,1,Graduate,NaN,3652,0.0,95.0,360.0,1.0,Semiurban,Y
576,LP002872,NaN,Yes,0,Graduate,No,3087,2210.0,136.0,360.0,0.0,Semiurban,N
579,LP002888,Male,No,0,Graduate,NaN,3182,2917.0,161.0,360.0,1.0,Urban,Y
588,LP002925,NaN,No,0,Graduate,No,4750,0.0,94.0,360.0,1.0,Semiurban,Y
592,LP002933,NaN,No,3+,Graduate,Yes,9357,0.0,292.0,360.0,1.0,Semiurban,Y
600,LP002949,Female,No,3+,Graduate,NaN,416,41667.0,350.0,180.0,NaN,Urban,N
601,LP002950,Male,Yes,0,Not Graduate,NaN,2894,2792.0,155.0,360.0,1.0,Rural,Y

In [124]:
#mode imputation -> Replace missing values with most frequent value.
categorical_cols = ['Gender', 'Married','Self_Employed']
for col in categorical_cols:
    mode_val = df[col].mode()[0]
    print(f"For {col} :  {mode_val}")
    for c in range(len(df[col])):
        if pd.isnull(df.loc[c,col]):
            df.loc[c,col] = mode_val
df[['Gender', 'Married','Self_Employed']].info()

For Gender :  Male
For Married :  Yes
For Self_Employed :  No
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender         614 non-null    object
 1   Married        614 non-null    object
 2   Self_Employed  614 non-null    object
dtypes: object(3)
memory usage: 14.5+ KB

In [125]:
df.loc[11,"Self_Employed"]
df.head(25)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
10,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,Y
11,LP001027,Male,Yes,2,Graduate,No,2500,1840.0,109.0,360.0,1.0,Urban,Y
12,LP001028,Male,Yes,2,Graduate,No,3073,8106.0,200.0,360.0,1.0,Urban,Y
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
14,LP001030,Male,Yes,2,Graduate,No,1299,1086.0,17.0,120.0,1.0,Urban,Y
15,LP001032,Male,No,0,Graduate,No,4950,0.0,125.0,360.0,1.0,Urban,Y
16,LP001034,Male,No,1,Not Graduate,No,3596,0.0,100.0,240.0,NaN,Urban,Y
17,LP001036,Female,No,0,Graduate,No,3510,0.0,76.0,360.0,0.0,Urban,N
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,N
19,LP001041,Male,Yes,0,Graduate,No,2600,3500.0,115.0,NaN,1.0,Urban,Y
20,LP001043,Male,Yes,0,Not Graduate,No,7660,0.0,104.0,360.0,0.0,Urban,N
21,LP001046,Male,Yes,1,Graduate,No,5955,5625.0,315.0,360.0,1.0,Urban,Y
22,LP001047,Male,Yes,0,Not Graduate,No,2600,1911.0,116.0,360.0,0.0,Semiurban,N
23,LP001050,Male,Yes,2,Not Graduate,No,3365,1917.0,112.0,360.0,0.0,Rural,N
24,LP001052,Male,Yes,1,Graduate,No,3717,2925.0,151.0,360.0,NaN,Semiurban,N

In [126]:
df['Loan_Amount_Term'].describe()

count    600.00000
mean     342.00000
std       65.12041
min       12.00000
25%      360.00000
50%      360.00000
75%      360.00000
max      480.00000
Name: Loan_Amount_Term, dtype: float64

In [127]:
for i in range(len(df)):
    mean_value = df["Loan_Amount_Term"].mean()
    if pd.isnull(df.loc[i,"Loan_Amount_Term"]):
        df.loc[i,"Loan_Amount_Term"] = mean_value

df["Loan_Amount_Term"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 614 entries, 0 to 613
Series name: Loan_Amount_Term
Non-Null Count  Dtype
--------------  -----
614 non-null    float64
dtypes: float64(1)
memory usage: 4.9 KB

In [128]:
for i in range(len(df)):
    mode_val = df['Credit_History'].mode()[0]
    if pd.isnull(df.loc[i,'Credit_History']):
        df.loc[i,'Credit_History'] = mode_val
df['Credit_History'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 614 entries, 0 to 613
Series name: Credit_History
Non-Null Count  Dtype
--------------  -----
614 non-null    float64
dtypes: float64(1)
memory usage: 4.9 KB

In [132]:
#Regression Imputation
from sklearn.linear_model import LinearRegression

train = df[df['LoanAmount'].notnull()]
# train.info()

test = df[df['LoanAmount'].isna()]
# test.info()

X_train = train[['CoapplicantIncome']]
Y_train = train['LoanAmount']

model = LinearRegression()
model.fit(X_train,Y_train)

print(df["LoanAmount"].info())

prediction = model.predict(test[['CoapplicantIncome']])
prediction = list(prediction)
print(prediction)
index = 0
for i in range(len(df)):
    if pd.isnull(df.loc[i,"LoanAmount"]):
        df.loc[i,"LoanAmount"]= prediction[index]
        index+=1

print(df.info())

<class 'pandas.core.series.Series'>
RangeIndex: 614 entries, 0 to 613
Series name: LoanAmount
Non-Null Count  Dtype
--------------  -----
593 non-null    float64
dtypes: float64(1)
memory usage: 4.9 KB
None
[np.float64(148.5383845932043), np.float64(138.77684705216544), np.float64(138.77684705216544), np.float64(138.77684705216544), np.float64(138.77684705216544), np.float64(155.69778996921542), np.float64(138.77684705216544), np.float64(146.52185022938062), np.float64(138.77684705216544), np.float64(138.77684705216544), np.float64(138.77684705216544), np.float64(146.28572208373382), np.float64(138.77684705216544), np.float64(153.586804347133), np.float64(138.77684705216544), np.float64(144.08973032921853), np.float64(146.34711540160197), np.float64(148.63283585146306), np.float64(138.77684705216544), np.float64(149.99293397038863), np.float64(156.72258612132256)]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB
None

In [136]:
#Categorical → Numerical
from sklearn.preprocessin
g# import OrdinalEncoder
# TWO things happen here:

# 1. fit()
# 👉 Learn all unique categories
# 2. transform()
# 👉 Convert them into numbers

model = OrdinalEncoder()
categorical_cols = ['Gender', 'Married','Self_Employed','Property_Area','Loan_Status','Education']
for col in categorical_cols:
    df[col] = model.fit_transform(df[[col]])

df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,1.0,0.0,0,0.0,0.0,5849,0.0,148.536688,360.0,1.0,2.0,1.0
1,LP001003,1.0,1.0,1,0.0,0.0,4583,1508.0,138.775281,360.0,1.0,0.0,0.0
2,LP001005,1.0,1.0,0,0.0,1.0,3000,0.0,138.775281,360.0,1.0,2.0,1.0
3,LP001006,1.0,1.0,0,1.0,0.0,2583,2358.0,138.775281,360.0,1.0,2.0,1.0
4,LP001008,1.0,0.0,0,0.0,0.0,6000,0.0,138.775281,360.0,1.0,2.0,1.0

In [139]:
#Random sample
df['Dependents'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 614 entries, 0 to 613
Series name: Dependents
Non-Null Count  Dtype
--------------  -----
599 non-null    object
dtypes: object(1)
memory usage: 4.9+ KB

In [153]:
nonnull_values = df['Dependents'].dropna()
print(nonnull_values)
nullcount = df['Dependents'].isna().sum()
print(nullcount)

0       0
1       1
2       0
3       0
4       0
       ..
609     0
610    3+
611     1
612     2
613     0
Name: Dependents, Length: 599, dtype: object
15

In [156]:
random = nonnull_values.sample(nullcount,random_state=0)
# print(random)
random = list(random)
print(random)

index = 0 ;
for i in range(len(df)):
    if pd.isnull(df.loc[i,"Dependents"]):
        df.loc[i,"Dependents"]= random[index]
        index+=1
print(df['Dependents'].info())

['0', '0', '0', '0', '1', '0', '0', '0', '0', '1', '1', '2', '2', '2', '0']
<class 'pandas.core.series.Series'>
RangeIndex: 614 entries, 0 to 613
Series name: Dependents
Non-Null Count  Dtype
--------------  -----
614 non-null    object
dtypes: object(1)
memory usage: 4.9+ KB
None